const { exec } = require('child_process');
const fs = require('fs');
const path = require('path');
const Anomaly = require('../models/Anomaly');

/**
 * Service to execute Gemini-generated remediation scripts on mock sandbox files.
 */
async function applyFix(anomalyId) {
  const anomaly = await Anomaly.findById(anomalyId);
  if (!anomaly) {
    throw new Error('Anomaly not found');
  }

  // Prevent concurrent executions
  if (anomaly.remediationStatus === 'EXECUTING') {
    console.warn(`[Remediator] Anomaly ${anomalyId} is already executing a fix.`);
    return;
  }

  console.log(`⚙️ [Remediator] Starting remediation for Anomaly ID: ${anomalyId} (${anomaly.service})`);

  // Reset logs and set status to EXECUTING
  anomaly.remediationStatus = 'EXECUTING';
  anomaly.remediationLogs = [`[SRE Terminal] Spawning auto-heal execution context...`];
  await anomaly.save();

  const scriptContent = anomaly.remediationScript;
  let commandToRun = scriptContent;
  let tempFilePath = '';

  try {
    // SRE Optimization: Extract inline Node execution into a temporary JavaScript file 
    // to bypass terminal escaping issues on Windows shell/PowerShell.
    if (scriptContent.trim().startsWith('node -e "') && scriptContent.trim().endsWith('"')) {
      const startIdx = scriptContent.indexOf('"') + 1;
      const endIdx = scriptContent.lastIndexOf('"');
      let innerJs = scriptContent.slice(startIdx, endIdx).trim();

      // Normalize escaped characters generated by JSON formatting
      innerJs = innerJs
        .replace(/\\"/g, '"')
        .replace(/\\n/g, '\n')
        .replace(/\\\\/g, '\\');

      const tempFileName = `temp_fix_${anomalyId}.js`;
      tempFilePath = path.join(__dirname, '../../sandbox', tempFileName);
      
      fs.writeFileSync(tempFilePath, innerJs, 'utf8');
      commandToRun = `node sandbox/${tempFileName}`;
      
      console.log(`⚙️ [Remediator] Extracted inline script to file: ${tempFileName}`);
      await Anomaly.findByIdAndUpdate(anomalyId, {
        $push: { remediationLogs: `[SRE Terminal] Extracted cross-platform JS payload to sandbox/${tempFileName}` }
      });
    }

    const execOptions = {
      cwd: path.resolve(__dirname, '../../') // Run from backend root so 'sandbox/...' paths resolve correctly
    };

    // Log the command about to be run
    await Anomaly.findByIdAndUpdate(anomalyId, {
      $push: { remediationLogs: `[SRE Terminal] Executing: ${commandToRun}` }
    });

    const child = exec(commandToRun, execOptions);

    // Stream stdout to MongoDB logs
    child.stdout.on('data', async (data) => {
      const lines = data.toString().split('\n').filter(l => l.trim() !== '');
      await Anomaly.findByIdAndUpdate(anomalyId, {
        $push: { remediationLogs: { $each: lines } }
      });
    });

    // Stream stderr to MongoDB logs
    child.stderr.on('data', async (data) => {
      const lines = data.toString().split('\n').filter(l => l.trim() !== '').map(l => `[ERROR] ${l}`);
      await Anomaly.findByIdAndUpdate(anomalyId, {
        $push: { remediationLogs: { $each: lines } }
      });
    });

    // Handle process close
    child.on('close', async (code) => {
      const finalStatus = code === 0 ? 'SUCCESS' : 'FAILED';
      const statusLog = code === 0 
        ? `[SRE Terminal] Auto-remediation COMPLETED successfully (exit code 0).`
        : `[SRE Terminal] Auto-remediation FAILED (exit code ${code}).`;

      // Update anomaly
      const updateData = {
        remediationStatus: finalStatus,
        $push: { remediationLogs: statusLog }
      };

      if (code === 0) {
        updateData.resolved = true; // Automatically resolve anomaly on success
      }

      await Anomaly.findByIdAndUpdate(anomalyId, updateData);

      // Clean up temporary script
      if (tempFilePath && fs.existsSync(tempFilePath)) {
        fs.unlinkSync(tempFilePath);
        console.log(`⚙️ [Remediator] Cleaned up temporary script file.`);
      }
    });

  } catch (err) {
    console.error(`❌ [Remediator] Execution exception for Anomaly ${anomalyId}:`, err);
    
    await Anomaly.findByIdAndUpdate(anomalyId, {
      remediationStatus: 'FAILED',
      $push: { remediationLogs: `[SRE Terminal] CRITICAL EXCEPTION: ${err.message}` }
    });

    if (tempFilePath && fs.existsSync(tempFilePath)) {
      fs.unlinkSync(tempFilePath);
    }
  }
}

module.exports = {
  applyFix
};
